version: "3"

services:
  app:
    build: .
    container_name: xp_challenge
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      API_URL: ${API_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
  db:
    container_name: xp_challenge_db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  default:
    name: xp_challenge_net
